const Product = [
  {
    plate: "Egg",
    price: "10.99$",
    imageUrl: "/egg.png",
    category: "best-seller",
    stock: 5,
    id: "1",
  },

  {
    plate: "Tofu",
    price: "15.99$",
    imageUrl: "/tofu.png",
    category: "best-seller",
    stock: 2,
    id: "2",
  },

  {
    plate: "Pizza",
    price: "20.99$",
    imageUrl: "/pizza.png",
    category: "entradas",
    stock: 7,
    id: "3",
  },
  {
    plate: "Hot Dog",
    price: "5$",
    imageUrl: "/hotdog.png",
    category: "best-seller",
    stock: 8,
    id: "4",
  },
  {
    plate: "Salad",
    price: "8$",
    imageUrl: "/salad.png",
    category: "principales",
    stock: 0,
    id: "5",
  },
  {
    plate: "Soup",
    price: "5$",
    imageUrl: "/soup.png",
    category: "entradas",
    stock: 15,
    id: "6",
  },
  {
    plate: "Shawarma",
    price: "10$",
    imageUrl: "/shawarma.png",
    category: "principales",
    stock: 20,
    id: "7",
  },
  {
    plate: "Muffin",
    price: "2$",
    imageUrl: "/postre.png",
    category: "postres",
    stock: 5,
    id: "8",
  },
  {
    plate: "Onam Alakan",
    price: "15$",
    imageUrl: "/onamalakan.png",
    category: "principales",
    stock: 12,
    id: "9",
  },
  {
    plate: "Fudge de Chocolate",
    price: "5$",
    imageUrl: "/fudgechocolate.png",
    category: "postres",
    stock: 5,
    id: "10",
  },
  {
    plate: "Pan de Brioche",
    price: "5$",
    imageUrl: "/brioche.png",
    category: "postres",
    stock: 0,
    id: "11",
  },
];

export default Product;
